### ISSUE TITLE
Bug: Bows only work in creative mode

### ISSUE THREAD

**Issue by ghost** [NienteSpigotSenzaJava/UltimateBows#1]
All bows work in creative mode but when I switch the gamemode to survival they stop working and even after switching back to creative they're still broken.

I think that happens because you compare the bow the player has in his hand with the bow of your BowManager.java
`if (item.isSimilar(BowsManager.getBowItem(BowsManager.getBowByName("destructionBow"))))`

But when you use a bow in survival the durability drops and then the items are technically not the same anymore.

**Comment by NienteSpigotSenzaJava** [comment]
Got it, would you mind to make a pull request? That would be great.

If you don't have time for that, i'll fix it later.

**Comment by ghost** [comment]
Fixed the bug with pr #3
