### ISSUE TITLE
Suggestion: Craftable bows

### ISSUE THREAD

**Issue by ghost** [NienteSpigotSenzaJava/UltimateBows#10]
Ok other idea.

Maybe you could add that the bows are also craftable, like:

1 bow + 8 tnt = explosive bow
1 bow + 8 ender pearls = teleport bow
1 bow + 8 lava buckets = lava bow
1 bow + 8 dia pickaxes = destruction bow__

**Comment by NienteSpigotSenzaJava** [comment]
I'll try to add this tonight/tomorrow
