### ISSUE TITLE
Suggestion: More permissions

### ISSUE THREAD

**Issue by ghost** [NienteSpigotSenzaJava/UltimateBows#11]
I think it would be a good feature for server owner if they could give players permissions for crafting the different bows and arrows (#9 and #10) and also permissions to use them (for every bow an extra permission)

for example: ubows.craft.mobBow, ubows.craft.diamondArrow, ubows.use.explosiveBow and ubows.use.netheriteArrow

**Comment by NienteSpigotSenzaJava** [comment]
implemented permissions for using bows.
