### ISSUE TITLE
Suggestion: Potion bow

### ISSUE THREAD

**Issue by ghost** [NienteSpigotSenzaJava/UltimateBows#8]
Maybe you can also add a bow who spawns random splash potions

**Comment by NienteSpigotSenzaJava** [comment]
Adding this in addiction to fireBow just tonight.

**Comment by NienteSpigotSenzaJava** [comment]
I just added the bow but it doesn't seem to work as it should.
It just spawns the potion but it doesn't have any effect, you'll maybe want to check it please?

**Comment by NienteSpigotSenzaJava** [comment]
Closing this since I don't have much time to work on new features anymore.
