### ISSUE TITLE
Suggestion: Multiplier arrows

### ISSUE THREAD

**Issue by ghost** [NienteSpigotSenzaJava/UltimateBows#9]
Ok I think I had a great idea. What's about arrows you can craft like:

1 arrow + 8 stone = 1 stone arrow
1 stone arrow + 8 iron = 1 iron arrow
then gold, smaragd, dia, netherite

Then every custom arrow has an multiplier, for example:
- stone *2
- iron *3
- gold *5
- smaragd * 10
- dia *25
- netherite *50

(just example values, maybe will cause lags if so high)

Then the multiplier is applied to the bows:
- Mob bow with dia arrow = 25 Mobs
- Explosive bow with smaragd = 10 times bigger explosion
- etc.

Maybe you could add a config option for cooldowns where you can set a cooldown for every arrow sort. So the players can't shoot like 10 netherite arrows and spawn 500 mobs in like 30 seconds or so.

And maybe there could be also a config option for the multipliers so the server admin can set them himself to values he want.

I know it's a complicated feature but I think it would be cool. But of course you have not to add it if its too hard for you. Then I will add it when I have time. But if you want to add it yourself and need any help feel free to ask.

(btw sorry for spelling and bad formating typed this fast on mobile ^^)

**Comment by NienteSpigotSenzaJava** [comment]
Well i think it's a good idea too, but this means the plugin will have literally another "life", what about making a new plugin together? I'm new to Java and Spigot so it is complicated for me, but if you want we can collaborate and create UltimateArrows together xD

**Comment by ghost** [comment]
xD

I see your point but I dont see what use an extra plugin would have. I mean if we put this in an extra plugin the extra plugin would have no other use expect for ubows.

**Comment by ghost** [comment]
So the only result would by that the user would have to download 2 plugins instead of 1 and the 2nd plugin would be completly useless without ubows.

**Comment by NienteSpigotSenzaJava** [comment]
> xD
> 
> I see your point but I dont see what use an extra plugin would have. I mean if we put this in an extra plugin the extra plugin would have no other use expect for ubows.

Basically, UltimateBows adds new bows, UltimateArrows adds new arrows, we can make it as an add-on and standalone plugin. A player will be able to use only UltimateBows or only UltimateArrows or both.

**Comment by ghost** [comment]
But what use would a standalone UltimateArrows have?

**Comment by NienteSpigotSenzaJava** [comment]
> But what use would a standalone UltimateArrows have?

I explained myself wrong, i meant to make a new plugin that basically adds explosive arrows etc instead of bows, then we could add special arrows in UltimateBows of course.

**Comment by ghost** [comment]
So like the same plugin expect the bows are default and the arrows add the effects etc.?

**Comment by ghost** [comment]
If so what would happen if a player shoots an explosive arrow with an explosive bow? Or an teleport arrow with an lava bow. I mean this would mean death to the player lol.

**Comment by NienteSpigotSenzaJava** [comment]
> If so what would happen if a player shoots an explosive arrow with an explosive bow? Or an teleport arrow with an lava bow. I mean this would mean death to the player lol.

Ok, didn't think about that lol.
You're right, another plugin isn't really the solution, it's better adding the feature you just proposed.

**Comment by ghost** [comment]
xD

Leave this issue as it is and add the other features first. I'll think about this a bit and maybe I'll find a solution.
